#
# Generated by the NeXT Project Builder.
#
# NOTE: Do NOT change this file -- Project Builder maintains it.
#
# Put all of your customizations in files called Makefile.preamble
# and Makefile.postamble (both optional), and Makefile will include them.
#

NAME = HeresColor

PROJECTVERSION = 1.1
LANGUAGE = English

APPICON = IconMan.tiff
DOCICONS = HERE.tiff

LOCAL_RESOURCES = Changes.nib HeresColor.nib Info.nib InputProfile.nib \
                  MonitorCalibrator.nib OpenPanelAccessory.nib \
                  OutputProfInsp.nib PrintPanelAccessory.nib \
                  Registration.nib SavePanelAccessory.nib \
                  ScannerCalibrator.nib

CLASSES = Change.m ChangeManager.m ColorLinks.m Controller.m Curve.m \
          GammaView.m ImageDocument.m ImageScrollView.m ImageView.m \
          MonitorCalibrator.m MyDBImageView.m OPISupport.m \
          OutputProfileInspector.m PatternView.m PrinterChipsView.m \
          ScannerCalibrator.m Slidey.m Spin.m

HFILES = Change.h ChangeManager.h ColorLinks.h Controller.h Curve.h \
         GammaView.h HEREpsw.h ImageDocument.h ImageScrollView.h \
         ImageView.h MonitorCalibrator.h MyDBImageView.h OPISupport.h \
         OutputProfileInspector.h PatternView.h PrinterChipsView.h \
         Registration.h ScannerCalibrator.h Slidey.h Spin.h

MFILES = HeresColor_main.m ProgressView.m Registration.m HEREutils.m \
         InkmodelCheck.m

CFILES = CmsLibStub.c Errors.c

PSWFILES = HEREpsw.psw

OTHERSRCS = Makefile.preamble Makefile Makefile.postamble


MAKEFILEDIR = /NextDeveloper/Makefiles/app
INSTALLDIR = $(HOME)/Apps
INSTALLFLAGS = -c -s -m 755
SOURCEMODE = 444

ICONSECTIONS =	-sectcreate __ICON app IconMan.tiff \
		-sectcreate __ICON HERE HERE.tiff

LIBS = -ldbkit_p -lMedia_s -lNeXT_s
DEBUG_LIBS = $(LIBS)
PROF_LIBS = $(LIBS)


-include Makefile.preamble

include $(MAKEFILEDIR)/app.make

-include Makefile.postamble

-include Makefile.dependencies
